name: pekosz-nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10  
  - augur=26.0.0
  - awscli=1.27.9
  - epiweeks=2.1.2
  - iqtree>=2.2.0
  - mafft=7.526
  - nextclade=3.8.2
  - seaborn>=0.11
  - seqkit>=2.2.0
  - csvtk=0.31.0
  - tsv-utils=2.2.3
  - tabulate=0.9.0
  - xlrd=1.*
  - pathogen-embed=3.1.0
  - blast=2.16.0
  - pip

  - pip:
      - snakemake==9.13.5  
